-- NovaCrypto database schema for Supabase/Postgres.
-- Run this in Supabase SQL Editor.
-- Do not store the publishable key or service-role key in this file.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.balances (
  user_email text primary key references public.users(email) on update cascade on delete cascade,
  amount numeric(24, 8) not null default 0 check (amount >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.holdings (
  user_email text not null references public.users(email) on update cascade on delete cascade,
  asset text not null check (asset = upper(asset)),
  quantity numeric(30, 12) not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_email, asset)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_email text not null references public.users(email) on update cascade on delete cascade,
  asset text not null check (asset = upper(asset)),
  side text not null check (side in ('buy', 'sell')),
  order_type text not null default 'Market' check (order_type in ('Market', 'Limit', 'Stop')),
  amount numeric(30, 12) not null check (amount > 0),
  price numeric(24, 8) not null check (price > 0),
  total numeric(24, 8) not null check (total > 0),
  status text not null default 'open' check (status in ('open', 'filled', 'cancelled', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.deposits (
  id bigint generated by default as identity primary key,
  user_email text not null references public.users(email) on update cascade on delete cascade,
  amount numeric(24, 8) not null check (amount > 0),
  method text not null default 'crypto',
  wallet_network text not null default 'bitcoin',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  balance_after_approval numeric(24, 8),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  user_email text not null references public.users(email) on update cascade on delete cascade,
  amount numeric(24, 8) not null check (amount > 0),
  withdrawal_name text not null,
  withdrawal_address text not null,
  withdrawal_network text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_email text not null unique references public.users(email) on update cascade on delete cascade,
  plan text not null default 'Pro',
  price text not null,
  payment_method text not null default 'crypto',
  wallet_address text,
  wallet_network text,
  crypto_amount numeric(24, 12),
  receipt_name text,
  receipt_type text,
  receipt_data text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  payment_note text default '',
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_email text references public.users(email) on update cascade on delete set null,
  author text not null,
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.customer_message_drafts (
  day text primary key check (day in ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday')),
  subject text not null default '',
  body text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_message_log (
  id bigint generated by default as identity primary key,
  user_email text not null references public.users(email) on update cascade on delete cascade,
  day text not null check (day in ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday')),
  subject text not null,
  body text not null,
  sent_at timestamptz not null default now()
);

create index if not exists orders_user_created_idx on public.orders(user_email, created_at desc);
create index if not exists deposits_user_created_idx on public.deposits(user_email, created_at desc);
create index if not exists withdrawals_user_created_idx on public.withdrawals(user_email, created_at desc);
create index if not exists payments_user_status_idx on public.payments(user_email, status);
create unique index if not exists payments_user_email_unique_idx on public.payments(user_email);
create index if not exists chat_messages_created_idx on public.chat_messages(created_at desc);
create index if not exists customer_message_log_user_sent_idx on public.customer_message_log(user_email, sent_at desc);
create index if not exists customer_message_log_day_sent_idx on public.customer_message_log(day, sent_at desc);

-- Keep modified timestamps current when balances or holdings change.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists balances_set_updated_at on public.balances;
create trigger balances_set_updated_at
before update on public.balances
for each row execute function public.set_updated_at();

drop trigger if exists holdings_set_updated_at on public.holdings;
create trigger holdings_set_updated_at
before update on public.holdings
for each row execute function public.set_updated_at();

drop trigger if exists customer_message_drafts_set_updated_at on public.customer_message_drafts;
create trigger customer_message_drafts_set_updated_at
before update on public.customer_message_drafts
for each row execute function public.set_updated_at();

insert into public.customer_message_drafts (day)
values ('monday'), ('tuesday'), ('wednesday'), ('thursday'), ('friday'), ('saturday')
on conflict (day) do nothing;

-- Server-side app: keep these tables inaccessible to the browser's publishable key.
-- Your Node server should connect with a Supabase server secret and enforce authorization.
alter table public.users enable row level security;
alter table public.balances enable row level security;
alter table public.holdings enable row level security;
alter table public.orders enable row level security;
alter table public.deposits enable row level security;
alter table public.withdrawals enable row level security;
alter table public.payments enable row level security;
alter table public.chat_messages enable row level security;
alter table public.customer_message_drafts enable row level security;
alter table public.customer_message_log enable row level security;

-- No anon/authenticated policies are intentionally created here.
-- Add narrowly scoped policies only after migrating the app from custom passwords
-- to Supabase Auth, or access these tables only through your server API.
